<?php 
class Timeoff_Model extends CI_Model
{
	public function addAutoGeneratedPuzzle($param) 
	{			
		$data = array(
					'puzzle_date' => $param['puzzleDate'],
					'puzzle_recorded_steps' => $param['sRecordedSteps']
				);

		$this->db->insert('puzzle', $data);			
		return $this->db->insert_id();
	}	
}	
?>
